### ISSUE TITLE
Auto-Scroll not working

### ISSUE THREAD

**Issue by hardikk2002** [hardikk2002/Dev-Essentials#7]
Auto-scroll is not working, when a new tab opens up beneath the Index popup page.

The directory that may need changes
```
src > components > Popop.js
```
Package that could help: [React-Scroll-to-Bottom](https://www.npmjs.com/package/react-scroll-to-bottom).

**Comment by rahulshawdev** [comment]
Can you explain it in brief??

**Comment by hardikk2002** [comment]
Hey @rahulshawdev!

The issue is that when someone clicks on any of the initially given options (like, Blogs space, Coding contests and ...) then that particular component that is attached to the Given Option appends at the bottom.

So, the enhancement of which I was saying is that **on clicking, the window (view area) should automatically scroll to the bottom when it has something new below it.**

That's why I have linked [React-Scroll-to-Bottom](https://www.npmjs.com/package/react-scroll-to-bottom) npm package it may help to do this task. 💫 

Let me know if it is still unclear to you.

**Comment by RamanSharma100** [comment]
getting error while installing dependencies in windows

**Comment by hardikk2002** [comment]
@RamanSharma100 Please share the Error that you are getting, as this should not be the case I think.

**Comment by RamanSharma100** [comment]
this is the error that I am getting while installing dependencies
![image](https://user-images.githubusercontent.com/56464662/132281341-f2e9d3b5-99d3-4c88-b3e6-439282013d63.png)

**Comment by RamanSharma100** [comment]
its the error related to os

**Comment by hardikk2002** [comment]
@RamanSharma100 its I think something related to package-lock.json. 
Once delete:
- Once package-lock.json
- package.json files
And then try 
''' 
npm install

'''

It will create new lock file and it should work then.
But I am not sure, still you can give it a try and reply if it works or not.

**Comment by RamanSharma100** [comment]
ya this worked thanks

**Comment by RamanSharma100** [comment]
while running the webpack popup is not able to compile and run

![image](https://user-images.githubusercontent.com/56464662/132288527-dc9b3ac8-189d-4da0-a38a-5dfa6d90234a.png)

![image](https://user-images.githubusercontent.com/56464662/132288551-5b5b582b-4656-4a04-80e4-4e9ee79da70f.png)

**Comment by RamanSharma100** [comment]
i think you haven't mentioned  @material-ui/core/utils package

**Comment by RamanSharma100** [comment]
working after installing material ui core i will also update the package.json

**Comment by hardikk2002** [comment]
@RamanSharma100 yes intall it, I don't know why it is showing that.
Run
- npm i @material-ui/core

It will resolve this error.

**Comment by RamanSharma100** [comment]
ya already done

**Comment by hardikk2002** [comment]
@RamanSharma100 That's awesome, few more things.

> inside src/entry/index-options.js

- You will not be able to access the /options.html route as Auth0 is used there, so it will give you the error, to check that page you might want to use your own client ID and Redirect URI **( those which are in the app right are now updated with new client ID in production)**.

- Also if you are trying to run in local host, then change 
> redirectUri="localhost:8080/options.html"

And if you are trying it using load unpack in your chrome then use
> redirectUri=window.location.origin
